export const categories = [
  "Electronics",
  "Fashion",
  "Home & Living",
  "Sports & Outdoors",
  "Beauty & Personal Care",
  "Books & Media",
];

export const dummyProducts = [
  {
    _id: "1",
    name: "Premium Wireless Headphones",
    description: "Experience crystal-clear audio with our premium wireless headphones. Features active noise cancellation, 40-hour battery life, and comfortable over-ear design. Perfect for music lovers and professionals.",
    price: 299.99,
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500"],
    stock: 15,
    featured: true,
    averageRating: 4.5,
    numReviews: 124,
  },
  {
    _id: "2",
    name: "Smart Watch Series 5",
    description: "Stay connected and track your fitness goals with our latest smartwatch. Features heart rate monitoring, GPS, sleep tracking, and seamless smartphone integration.",
    price: 399.99,
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500"],
    stock: 8,
    featured: true,
    averageRating: 4.8,
    numReviews: 89,
  },
  {
    _id: "3",
    name: "Designer Leather Bag",
    description: "Handcrafted from genuine Italian leather, this elegant bag combines style and functionality. Multiple compartments keep you organized while making a fashion statement.",
    price: 199.99,
    category: "Fashion",
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500"],
    stock: 20,
    featured: false,
    averageRating: 4.6,
    numReviews: 56,
  },
  {
    _id: "4",
    name: "Modern Table Lamp",
    description: "Elegant minimalist design with adjustable brightness. LED technology provides warm, energy-efficient lighting perfect for any room.",
    price: 79.99,
    category: "Home & Living",
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500"],
    stock: 12,
    featured: true,
    averageRating: 4.3,
    numReviews: 32,
  },
  {
    _id: "5",
    name: "Wireless Mechanical Keyboard",
    description: "Premium mechanical switches provide satisfying tactile feedback. Wireless connectivity, RGB backlighting, and ergonomic design for the ultimate typing experience.",
    price: 149.99,
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500"],
    stock: 25,
    featured: false,
    averageRating: 4.7,
    numReviews: 67,
  },
  {
    _id: "6",
    name: "Running Shoes Pro",
    description: "Lightweight, breathable, and designed for performance. Advanced cushioning technology reduces impact while maximizing energy return.",
    price: 129.99,
    category: "Sports & Outdoors",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500"],
    stock: 18,
    featured: true,
    averageRating: 4.9,
    numReviews: 143,
  },
  {
    _id: "7",
    name: "4K Ultra HD Camera",
    description: "Capture life's moments in stunning 4K resolution. Professional-grade features in a compact, user-friendly package. Includes 3 lenses and accessories.",
    price: 899.99,
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500"],
    stock: 5,
    featured: false,
    averageRating: 4.8,
    numReviews: 92,
  },
  {
    _id: "8",
    name: "Organic Cotton T-Shirt",
    description: "Soft, sustainable, and stylish. Made from 100% organic cotton with a perfect fit. Available in multiple colors.",
    price: 29.99,
    category: "Fashion",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500"],
    stock: 50,
    featured: false,
    averageRating: 4.4,
    numReviews: 28,
  },
  {
    _id: "9",
    name: "Smart Coffee Maker",
    description: "Wake up to freshly brewed coffee every morning. Programmable, app-controlled, and designed to brew the perfect cup every time.",
    price: 179.99,
    category: "Home & Living",
    images: ["https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500"],
    stock: 14,
    featured: false,
    averageRating: 4.5,
    numReviews: 45,
  },
  {
    _id: "10",
    name: "Yoga Mat Premium",
    description: "Extra-thick, non-slip surface provides superior comfort and stability. Eco-friendly materials, easy to clean, comes with carrying strap.",
    price: 49.99,
    category: "Sports & Outdoors",
    images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500"],
    stock: 30,
    featured: false,
    averageRating: 4.6,
    numReviews: 78,
  },
  {
    _id: "11",
    name: "Wireless Earbuds Pro",
    description: "True wireless freedom with premium sound quality. Active noise cancellation, touch controls, and 24-hour battery life with charging case.",
    price: 199.99,
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500"],
    stock: 22,
    featured: true,
    averageRating: 4.7,
    numReviews: 156,
  },
  {
    _id: "12",
    name: "Minimalist Backpack",
    description: "Sleek design meets maximum functionality. Padded laptop compartment, water-resistant fabric, and ergonomic straps for all-day comfort.",
    price: 89.99,
    category: "Fashion",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500"],
    stock: 16,
    featured: false,
    averageRating: 4.5,
    numReviews: 41,
  },
  {
    _id: "13",
    name: "Aromatherapy Diffuser",
    description: "Create a relaxing atmosphere with this elegant ultrasonic diffuser. LED color-changing lights, whisper-quiet operation, auto shut-off.",
    price: 39.99,
    category: "Home & Living",
    images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500"],
    stock: 28,
    featured: false,
    averageRating: 4.4,
    numReviews: 63,
  },
  {
    _id: "14",
    name: "Fitness Tracker Band",
    description: "Monitor your health 24/7. Track steps, heart rate, sleep quality, and more. Water-resistant with 7-day battery life.",
    price: 79.99,
    category: "Sports & Outdoors",
    images: ["https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500"],
    stock: 35,
    featured: false,
    averageRating: 4.3,
    numReviews: 87,
  },
  {
    _id: "15",
    name: "Luxury Skincare Set",
    description: "Complete daily skincare routine in one premium package. Includes cleanser, toner, serum, and moisturizer. Dermatologist-tested, suitable for all skin types.",
    price: 129.99,
    category: "Beauty & Personal Care",
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500"],
    stock: 19,
    featured: false,
    averageRating: 4.8,
    numReviews: 94,
  },
  {
    _id: "16",
    name: "Bestseller Book Collection",
    description: "Curated collection of 5 must-read contemporary novels. Perfect gift for book lovers or start your reading journey.",
    price: 59.99,
    category: "Books & Media",
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500"],
    stock: 40,
    featured: false,
    averageRating: 4.9,
    numReviews: 112,
  },
];

export const dummyReviews = [
  {
    _id: "1",
    userName: "John Smith",
    rating: 5,
    comment: "Absolutely amazing quality! Exceeded my expectations. The build quality is top-notch and it works flawlessly.",
    createdAt: new Date("2024-01-15"),
  },
  {
    _id: "2",
    userName: "Sarah Johnson",
    rating: 4,
    comment: "Great product overall. Fast shipping and good customer service. Only minor issue was the packaging could be better.",
    createdAt: new Date("2024-01-10"),
  },
  {
    _id: "3",
    userName: "Michael Chen",
    rating: 5,
    comment: "Best purchase I've made this year. The attention to detail is impressive. Highly recommend!",
    createdAt: new Date("2024-01-08"),
  },
  {
    _id: "4",
    userName: "Emily Davis",
    rating: 4,
    comment: "Very satisfied with this purchase. Good value for money. Would definitely buy again.",
    createdAt: new Date("2024-01-05"),
  },
];

export const dummyOrders = [
  {
    _id: "1",
    orderId: "ORD-2024-001",
    customer: { name: "John Doe", email: "john@example.com" },
    items: [
      { name: "Premium Wireless Headphones", quantity: 1, price: 299.99 },
      { name: "Wireless Mechanical Keyboard", quantity: 1, price: 149.99 },
    ],
    totalPrice: 479.98,
    status: "pending",
    createdAt: new Date("2024-01-15"),
  },
  {
    _id: "2",
    orderId: "ORD-2024-002",
    customer: { name: "Jane Smith", email: "jane@example.com" },
    items: [
      { name: "Smart Watch Series 5", quantity: 2, price: 399.99 },
    ],
    totalPrice: 809.98,
    status: "processing",
    createdAt: new Date("2024-01-15"),
  },
  {
    _id: "3",
    orderId: "ORD-2024-003",
    customer: { name: "Bob Johnson", email: "bob@example.com" },
    items: [
      { name: "Running Shoes Pro", quantity: 1, price: 129.99 },
      { name: "Fitness Tracker Band", quantity: 1, price: 79.99 },
    ],
    totalPrice: 219.98,
    status: "shipped",
    createdAt: new Date("2024-01-14"),
  },
  {
    _id: "4",
    orderId: "ORD-2024-004",
    customer: { name: "Alice Williams", email: "alice@example.com" },
    items: [
      { name: "4K Ultra HD Camera", quantity: 1, price: 899.99 },
    ],
    totalPrice: 909.99,
    status: "delivered",
    createdAt: new Date("2024-01-13"),
  },
  {
    _id: "5",
    orderId: "ORD-2024-005",
    customer: { name: "David Brown", email: "david@example.com" },
    items: [
      { name: "Smart Coffee Maker", quantity: 1, price: 179.99 },
      { name: "Aromatherapy Diffuser", quantity: 2, price: 39.99 },
    ],
    totalPrice: 269.97,
    status: "processing",
    createdAt: new Date("2024-01-14"),
  },
];
